
version: '3.7'

services:
  
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    restart: unless-stopped
    volumes:
      - ./node_modules:/app/node_modules
      - .:/app'
    environment:
      CHOKIDAR_USEPOLLING: "true"

  proxy:
    image: nginx:1.17.9-alpine
    ports:
      - "8000:80"
    restart: unless-stopped
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf


  
